services:
  JJS:
    image: ${DOCKER_REGISTRY-}jjs
    container_name: students.app
    build:
      context: .
      dockerfile: Dockerfile
  studentsDB:
    image: mysql:latest
    container_name: students.db
    environment:
      - MYSQL_ROOT_PASSWORD=147
      - MYSQL_DATABASE=studentsDB
    volumes:
      - ./.containers/database:/var/lib/mysql
    ports:
      - 3306:3306